spring:
  datasource:
    url: jdbc:mysql://parayo-db-dev-01.chqpt2saltad.us-east-2.rds.amazonaws.com:3306/parayo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: parayo
    password: parayopassword
    data-username: parayo
    data-password: parayopassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect